# Generated by Django 4.2.1 on 2023-06-11 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_count', models.IntegerField()),
                ('day', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
